version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    groups:
      go-modules:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
